/*
===============================================================================
Magnitude Analysis
===============================================================================
Purpose:
    - To quantify data and group results by specific dimensions.
    - For understanding data distribution across categories.

SQL Functions Used:
    - Aggregate Functions: SUM(), COUNT(), AVG()
    - GROUP BY, ORDER BY
===============================================================================
*/

-- Determine the total customers by country.
SELECT country, COUNT(customer_key) AS total_customer
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customer DESC;

-- Count the total customers based on gender.
SELECT gender, COUNT(customer_key) AS total_customer
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customer DESC;

-- Calculate the total products within each category.
SELECT category, COUNT(product_key) AS total_product
FROM gold.dim_products
GROUP BY category
ORDER BY total_product DESC;

-- Identify the average cost per category.
SELECT category, AVG(cost) AS avg_cost
FROM gold.dim_products
GROUP BY category
ORDER BY avg_cost DESC;

-- Compute the total revenue generated for each category.
SELECT p.category, SUM(s.sales_amount) AS total_revenue
FROM gold.fact_sales s
LEFT JOIN gold.dim_products p
ON s.product_key = p.product_key
GROUP BY p.category
ORDER BY total_revenue DESC;

-- Determine the revenue generated by each customer.
SELECT 
c.customer_key,
c.first_name,
c.last_name,
SUM(s.sales_amount) AS total_revenue
FROM gold.fact_sales s
LEFT JOIN gold.dim_customers c
ON s.customer_key = c.customer_key
GROUP BY 
c.customer_key,
c.first_name,
c.last_name
ORDER BY total_revenue DESC;

-- Analyze the distribution of sold items across different countries.
SELECT 
c.country,
SUM(s.quantity) AS sold_items
FROM gold.fact_sales s
LEFT JOIN gold.dim_customers c
ON s.customer_key = c.customer_key
GROUP BY 
c.country
ORDER BY sold_items DESC;

